/* Build the Compliance Matrix page for Power Pages.

   Output (portal/dist, committed - you do not need Node to deploy):

     cm-matrix.js                      React + the app, one minified file
     cm-matrix.css                     the stylesheet, brand fonts embedded
     compliance-matrix.webtemplate.liquid   the web template, with a content
                                            hash stamped in for cache-busting
     preview.html                      opens in any browser, sample data
     cm-site.css, cm-site.js           the site header and footer's styles and
                                       behaviour, for every other page
     site-header.webtemplate.liquid    replaces the Power Pages site header
     site-footer.webtemplate.liquid    replaces the Power Pages site footer
     site-preview.html                 the site header and footer over a mock
                                       portal page, rendered from the templates

   Two files to upload as web files, one template to paste. Fonts and images
   are embedded so there is nothing else to upload.

     node build.mjs          write dist/
     node build.mjs --check  exit 1 if dist/ is not what a fresh build makes */

import * as esbuild from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { PurgeCSS } from "purgecss";
import vm from "node:vm";
import { Liquid } from "liquidjs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");
const STYLES = join(SRC, "styles");
const walk = d => readdirSync(d).flatMap(n => { const p = join(d, n); return statSync(p).isDirectory() ? walk(p) : [p]; });
const DIST = join(ROOT, "dist");
const check = process.argv.includes("--check");

const read = p => readFileSync(p, "utf8");

/* ---------------- JavaScript ---------------- */
async function buildJs() {
  const r = await esbuild.build({
    entryPoints: [join(SRC, "main.jsx")],
    bundle: true,
    format: "iife",
    minify: true,
    target: ["es2019", "chrome90", "firefox90", "safari14", "edge90"],
    jsx: "automatic",
    loader: { ".png": "dataurl", ".svg": "dataurl" },
    define: { "process.env.NODE_ENV": '"production"' },
    legalComments: "none",
    charset: "utf8",
    write: false
  });
  const banner = "/* Syracuse University Compliance Matrix, Power Pages build. Generated by portal/build.mjs; edit portal/src. React (c) Meta Platforms, Inc., MIT licence. */\n";
  return escapeScript(banner + r.outputFiles[0].text);
}

/* Power Pages adds a CSP nonce to any "<script" it finds in a page's script
   text, which breaks string literals that contain one (React DOM builds a
   "<script><\/script>" string). Written as \x3Cscript the string means the
   same thing and there is nothing to rewrite. Esbuild emits "<script" only
   inside string, template and regular expression literals, where \x3C is an
   equivalent escape; the parse check below proves the result is still valid. */
function escapeScript(js) {
  const out = js.replace(/<(script)/gi, "\\x3C$1");
  if (/<script/i.test(out)) throw new Error("cm-matrix.js still contains <script");
  new vm.Script(out, { filename: "cm-matrix.js" }); // throws on a syntax error
  return out;
}

/* ---------------- CSS ----------------
   Order matters and matches the Claude design's <head>: brand fonts, brand
   tokens, the SU Digital Design System, the app layer, the detail screen,
   the Power Pages additions, then this build's extras (quick jump, back bar,
   the pieces the canvas app's structure adds). Only the DDS is purged: it is
   a 278 KB framework of which the page uses a small part; the rest was
   written for this app. */
async function buildCss() {
  const content = walk(SRC).filter(p => /\.(jsx?|mjs)$/.test(p)).map(p => ({ raw: read(p), extension: "js" }));
  const [dds] = await new PurgeCSS().purge({
    content,
    css: [{ raw: read(join(STYLES, "dds.css")) }],
    fontFace: false,
    keyframes: true,
    variables: false,
    safelist: {
      standard: ["html", "body", "on", "late", "ok", "warn", "due", "bad", "sm", "empty", "today", "out", "z", "rw", "gc", "quiet"],
      greedy: [/^risk/, /^pill/, /^t-/, /^osubpill/, /^button/, /^table/, /^cm-/]
    }
  });
  const inlineFonts = css => css.replace(/url\("fonts\/([^"]+)"\)/g, (m, f) =>
    `url("data:font/woff2;base64,${readFileSync(join(STYLES, "fonts", f)).toString("base64")}")`);
  const parts = [
    ["fonts", inlineFonts(read(join(STYLES, "fonts.css")))],
    ["tokens", read(join(STYLES, "tokens.css"))],
    ["dds", dds.css],
    ["app", read(join(STYLES, "app.css"))],
    ["detail", read(join(STYLES, "detail.css"))],
    ["portal", read(join(STYLES, "portal.css"))],
    ["extras", read(join(STYLES, "extras.css"))]
  ];
  const joined = parts.map(([n, css]) => `/* ---- ${n} ---- */\n${css}`).join("\n");
  const min = await esbuild.transform(joined, { loader: "css", minify: true, legalComments: "none" });
  return "/* Syracuse University Compliance Matrix, Power Pages build. Generated by portal/build.mjs; edit portal/src/styles. */\n" + min.code;
}

function preview() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Compliance Matrix preview (sample data)</title>
<!-- Generated by portal/build.mjs. Open this file in a browser: it runs the
     real page against the design prototype's sample records, in memory.
     Every screen and every write works; nothing is saved. -->
<link rel="stylesheet" href="cm-matrix.css">
</head>
<body>
<div id="cm-root" data-backend="sample"></div>
<script src="cm-matrix.js"></script>
</body>
</html>
`;
}

/* ---------------- site header and footer ----------------
   Styles and script for every page other than the matrix, scoped under
   .cmh / .cmf so the portal theme and they leave each other alone. The
   Block S rides in the stylesheet as a data URI, the brand faces too. */
const SITE = join(SRC, "site");
async function buildSite() {
  const logo = "data:image/png;base64," + readFileSync(join(SRC, "assets", "block-s.png")).toString("base64");
  const inlineFonts = css => css.replace(/url\("fonts\/([^"]+)"\)/g, (m, f) =>
    `url("data:font/woff2;base64,${readFileSync(join(STYLES, "fonts", f)).toString("base64")}")`);
  /* the header and footer only set Sherman Sans */
  const sans = read(join(STYLES, "fonts.css")).split("\n").filter(l => !/ShermanSerif|font-style:italic/.test(l)).join("\n");
  const cssIn = [inlineFonts(sans), read(join(SITE, "site.css")), `.cmh { --cm-logo: url("${logo}"); }`].join("\n");
  const css = (await esbuild.transform(cssIn, { loader: "css", minify: true, legalComments: "none" })).code;
  const js = (await esbuild.transform(read(join(SITE, "site.js")), { loader: "js", minify: true, legalComments: "none", target: "es2017" })).code;
  const head = "/* Syracuse University Compliance Matrix site header and footer. Generated by portal/build.mjs; edit portal/src/site. */\n";
  return { css: head + css, js: escapeScript(head + js) };
}

/* site-preview.html: the real templates, rendered by liquidjs against a
   mock site (a web link set with a dropdown, a signed-in administrator),
   over a page styled like the portal's Bootstrap theme */
async function sitePreview(header, footer) {
  const engine = new Liquid();
  engine.registerFilter("url_escape", v => encodeURIComponent(String(v ?? "")));
  const ctx = {
    settings: {},
    website: { name: "Office of Compliance" },
    request: { path: "/policies-and-training/", path_and_query: "/policies-and-training/" },
    user: { fullname: "Camila Ruiz", emailaddress1: "cruiz@syr.edu", roles: ["Authenticated Users", "Compliance Matrix Administrators"] },
    weblinks: { Default: { weblinks: [
      { name: "Home", url: "/", weblinks: [] },
      { name: "Compliance Matrix", url: "/compliance-matrix/", weblinks: [] },
      { name: "Policies and Training", url: "/policies-and-training/", is_sitemap_current: true, description: "Required training and the policies behind it", weblinks: [
        { name: "Annual compliance training", url: "/policies-and-training/annual/", description: "Who must complete it, and by when" },
        { name: "Conflict of interest", url: "/policies-and-training/coi/", description: "Disclosure and review" }] },
      { name: "Contact", url: "/contact/", weblinks: [] }] } },
    sitemap: {}
  };
  const h = (await engine.parseAndRender(header, ctx)).replace(/\/cm-site\.(css|js)\?v=/g, "cm-site.$1?v=");
  const f = await engine.parseAndRender(footer, ctx);
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Site header preview</title>
<!-- Generated by portal/build.mjs from site-header and site-footer, rendered
     against a mock site. The page body imitates the portal's Bootstrap
     theme, to show the header and footer are unaffected by it. -->
<style>
body { margin: 0; font-family: "Segoe UI", Arial, sans-serif; color: #333; }
a { color: #2168b6; text-decoration: underline; } a:hover { color: #0e3f75; }
button { background: #eee; border: 1px solid #999; padding: 6px 12px; border-radius: 4px; }
ul { padding-left: 40px; } h2 { font-size: 30px; }
.sectionBlockLayout { padding: 48px 0; } .container { width: min(1170px, calc(100% - 30px)); margin: 0 auto; }
.portalThemeColor1 { background: #f2f2f2; }
</style>
</head>
<body>
${h}
<div id="mainContent" role="main">
  <div class="sectionBlockLayout portalThemeColor1"><div class="container">
    <h2>Policies and Training</h2>
    <p>This stands in for any page on the site that keeps the website header and footer. Open the menus, press Ctrl K, or narrow the window.</p>
    <p><a href="#">A theme-styled link</a> <button type="button">A theme button</button></p>
  </div></div>
  <div class="sectionBlockLayout"><div class="container"><ul><li>Theme list item</li><li>Theme list item</li></ul></div></div>
</div>
${f}
</body>
</html>
`;
}

const js = await buildJs();
const css = await buildCss();
const version = createHash("sha256").update(js).update(css).digest("hex").slice(0, 12);
const template = read(join(ROOT, "power-pages", "compliance-matrix.webtemplate.liquid")).replaceAll("__VERSION__", version);
const site = await buildSite();
const siteVersion = createHash("sha256").update(site.js).update(site.css).digest("hex").slice(0, 12);
const siteHeader = read(join(ROOT, "power-pages", "site-header.webtemplate.liquid")).replaceAll("__VERSION__", siteVersion);
const siteFooter = read(join(ROOT, "power-pages", "site-footer.webtemplate.liquid"));

const files = {
  "cm-matrix.js": js,
  "cm-matrix.css": css,
  "compliance-matrix.webtemplate.liquid": template,
  "preview.html": preview(),
  "cm-site.css": site.css,
  "cm-site.js": site.js,
  "site-header.webtemplate.liquid": siteHeader,
  "site-footer.webtemplate.liquid": siteFooter,
  "site-preview.html": await sitePreview(siteHeader, siteFooter)
};

if (check) {
  const stale = Object.entries(files).filter(([n, t]) => !existsSync(join(DIST, n)) || read(join(DIST, n)) !== t).map(([n]) => n);
  if (/<script/i.test(js) || /<script/i.test(site.js)) { console.error("a built script contains <script; the build must write \\x3Cscript"); process.exit(1); }
  if (stale.length) {
    console.error("portal/dist is out of date: " + stale.join(", ") + "\nrun: (cd portal && npm run build)");
    process.exit(1);
  }
  console.log(`portal/dist is current (${Object.keys(files).length} files, version ${version})`);
} else {
  mkdirSync(DIST, { recursive: true });
  for (const [n, t] of Object.entries(files)) writeFileSync(join(DIST, n), t);
  const kb = s => (Buffer.byteLength(s) / 1024).toFixed(0) + " KB";
  console.log(`  cm-matrix.js   ${kb(js)}`);
  console.log(`  cm-matrix.css  ${kb(css)}`);
  console.log(`  compliance-matrix.webtemplate.liquid  version ${version}`);
  console.log(`  preview.html`);
  console.log(`  cm-site.css    ${kb(site.css)}`);
  console.log(`  cm-site.js     ${kb(site.js)}`);
  console.log(`  site-header.webtemplate.liquid, site-footer.webtemplate.liquid  version ${siteVersion}`);
  console.log(`  site-preview.html`);
}
