/* Build the Compliance Matrix page for Power Pages.

   Output (portal/dist, committed - you do not need Node to deploy):

     cm-matrix.js                      React + the app, one minified file
     cm-matrix.css                     the stylesheet (Verdana and Georgia are
                                       system fonts, so none are embedded)
     compliance-matrix.webtemplate.liquid   the web template, with a content
                                            hash stamped in for cache-busting
     preview.html                      opens in any browser, sample data

   Two files to upload as web files, one template to paste. The one image
   (the Block S) is embedded so there is nothing else to upload.

     node build.mjs          write dist/
     node build.mjs --check  exit 1 if dist/ is not what a fresh build makes */

import * as esbuild from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import vm from "node:vm";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");
const STYLES = join(SRC, "styles");
const DIST = join(ROOT, "dist");
const check = process.argv.includes("--check");

const read = p => readFileSync(p, "utf8");

/* ---------------- JavaScript ---------------- */
async function buildJs() {
  const r = await esbuild.build({
    entryPoints: [join(SRC, "main.jsx")],
    bundle: true,
    format: "iife",
    minify: true,
    target: ["es2019", "chrome90", "firefox90", "safari14", "edge90"],
    jsx: "automatic",
    loader: { ".png": "dataurl", ".svg": "dataurl" },
    define: { "process.env.NODE_ENV": '"production"' },
    legalComments: "none",
    charset: "utf8",
    write: false
  });
  const banner = "/* Syracuse University Compliance Matrix, Power Pages build. Generated by portal/build.mjs; edit portal/src. React (c) Meta Platforms, Inc., MIT licence. */\n";
  return escapeScript(banner + r.outputFiles[0].text);
}

/* Power Pages adds a CSP nonce to any "<script" it finds in a page's script
   text, which breaks string literals that contain one (React DOM builds a
   "<script><\/script>" string). Written as \x3Cscript the string means the
   same thing and there is nothing to rewrite. Esbuild emits "<script" only
   inside string, template and regular expression literals, where \x3C is an
   equivalent escape; the parse check below proves the result is still valid. */
function escapeScript(js) {
  const out = js.replace(/<(script)/gi, "\\x3C$1");
  if (/<script/i.test(out)) throw new Error("cm-matrix.js still contains <script");
  new vm.Script(out, { filename: "cm-matrix.js" }); // throws on a syntax error
  return out;
}

/* ---------------- CSS ---------------- */
async function buildCss() {
  const min = await esbuild.transform(read(join(STYLES, "cm.css")), { loader: "css", minify: true, legalComments: "none" });
  return "/* Syracuse University Compliance Matrix, Power Pages build. Generated by portal/build.mjs; edit portal/src/styles. */\n" + min.code;
}

function preview() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Compliance Matrix preview (sample data)</title>
<!-- Generated by portal/build.mjs. Open this file in a browser: it runs the
     real page against the design prototype's sample records, in memory.
     Every screen and every write works; nothing is saved. -->
<link rel="stylesheet" href="cm-matrix.css">
</head>
<body>
<div id="cm-root" data-backend="sample"></div>
<script src="cm-matrix.js"></script>
</body>
</html>
`;
}

const js = await buildJs();
const css = await buildCss();
const version = createHash("sha256").update(js).update(css).digest("hex").slice(0, 12);
const template = read(join(ROOT, "power-pages", "compliance-matrix.webtemplate.liquid")).replaceAll("__VERSION__", version);

const files = {
  "cm-matrix.js": js,
  "cm-matrix.css": css,
  "compliance-matrix.webtemplate.liquid": template,
  "preview.html": preview()
};

if (check) {
  const stale = Object.entries(files).filter(([n, t]) => !existsSync(join(DIST, n)) || read(join(DIST, n)) !== t).map(([n]) => n);
  if (/<script/i.test(js)) { console.error("cm-matrix.js contains <script; the build must write \\x3Cscript"); process.exit(1); }
  if (stale.length) {
    console.error("portal/dist is out of date: " + stale.join(", ") + "\nrun: (cd portal && npm run build)");
    process.exit(1);
  }
  console.log(`portal/dist is current (${Object.keys(files).length} files, version ${version})`);
} else {
  mkdirSync(DIST, { recursive: true });
  for (const [n, t] of Object.entries(files)) writeFileSync(join(DIST, n), t);
  const kb = s => (Buffer.byteLength(s) / 1024).toFixed(0) + " KB";
  console.log(`  cm-matrix.js   ${kb(js)}`);
  console.log(`  cm-matrix.css  ${kb(css)}`);
  console.log(`  compliance-matrix.webtemplate.liquid  version ${version}`);
  console.log(`  preview.html`);
}
