/* Build the Compliance Matrix page for Power Pages.

   Output (portal/dist, committed - you do not need Node to deploy):

     cm-matrix.js                      React + the app, one minified file
     cm-matrix.css                     the design's CSS, fonts embedded
     compliance-matrix.webtemplate.liquid   the web template, with a content
                                            hash stamped in for cache-busting
     preview.html                      opens in any browser, sample data

   Two files to upload as web files, one template to paste. Fonts and images
   are embedded so there is nothing else to upload and nothing to go missing.

     node build.mjs          write dist/
     node build.mjs --check  exit 1 if dist/ is not what a fresh build makes */

import * as esbuild from "esbuild";
import { PurgeCSS } from "purgecss";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, "src");
const STYLES = join(SRC, "styles");
const DIST = join(ROOT, "dist");
const check = process.argv.includes("--check");

const read = p => readFileSync(p, "utf8");
const walk = dir => readdirSync(dir).flatMap(n => {
  const p = join(dir, n);
  return statSync(p).isDirectory() ? walk(p) : [p];
});

/* ---------------- JavaScript ---------------- */
async function buildJs() {
  const r = await esbuild.build({
    entryPoints: [join(SRC, "main.jsx")],
    bundle: true,
    format: "iife",
    minify: true,
    target: ["es2019", "chrome90", "firefox90", "safari14", "edge90"],
    jsx: "automatic",
    loader: { ".png": "dataurl", ".svg": "dataurl" },
    define: { "process.env.NODE_ENV": '"production"' },
    legalComments: "none",
    charset: "utf8",
    write: false
  });
  const banner = "/* Syracuse University Compliance Matrix - Power Pages build. Generated by portal/build.mjs; edit portal/src. React (c) Meta Platforms, Inc., MIT licence. */\n";
  return banner + r.outputFiles[0].text;
}

/* ---------------- CSS ----------------
   Order matters and matches the design's <head>: brand fonts, brand tokens,
   the SU Digital Design System, the app layer, the detail screen, then the
   Power Pages additions. Only the DDS is purged - it is a 278 KB framework of
   which the page uses a small part; the rest was written for this app. */
async function buildCss() {
  const content = walk(SRC).filter(p => /\.(jsx?|mjs)$/.test(p)).map(p => ({ raw: read(p), extension: "js" }));
  const [dds] = await new PurgeCSS().purge({
    content,
    css: [{ raw: read(join(STYLES, "dds.css")) }],
    fontFace: false,
    keyframes: true,
    variables: false,
    safelist: {
      standard: ["html", "body", "on", "late", "ok", "warn", "due", "bad", "sm", "empty", "today", "out", "z", "rw", "gc", "quiet"],
      greedy: [/^risk/, /^pill/, /^t-/, /^osubpill/, /^button/, /^table/, /^cm-/]
    }
  });
  const inlineFonts = css => css.replace(/url\("fonts\/([^"]+)"\)/g, (m, f) =>
    `url("data:font/woff2;base64,${readFileSync(join(STYLES, "fonts", f)).toString("base64")}")`);
  const parts = [
    ["fonts", inlineFonts(read(join(STYLES, "fonts.css")))],
    ["tokens", read(join(STYLES, "tokens.css"))],
    ["dds", dds.css],
    ["app", read(join(STYLES, "app.css"))],
    ["detail", read(join(STYLES, "detail.css"))],
    ["portal", read(join(STYLES, "portal.css"))]
  ];
  const joined = parts.map(([n, css]) => `/* ---- ${n} ---- */\n${css}`).join("\n");
  const min = await esbuild.transform(joined, { loader: "css", minify: true, legalComments: "none" });
  return { css: "/* Syracuse University Compliance Matrix - Power Pages build. Generated by portal/build.mjs; edit portal/src/styles. */\n" + min.code, ddsBefore: read(join(STYLES, "dds.css")).length, ddsAfter: dds.css.length };
}

function preview() {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Compliance Matrix — preview with sample data</title>
<!-- Generated by portal/build.mjs. Open this file in a browser: it runs the
     real page against the design prototype's sample records, in memory.
     Every screen and every write works; nothing is saved. -->
<link rel="stylesheet" href="cm-matrix.css">
</head>
<body>
<div id="cm-root" data-backend="sample"></div>
<script src="cm-matrix.js"></script>
</body>
</html>
`;
}

const js = await buildJs();
const { css, ddsBefore, ddsAfter } = await buildCss();
const version = createHash("sha256").update(js).update(css).digest("hex").slice(0, 12);
const template = read(join(ROOT, "power-pages", "compliance-matrix.webtemplate.liquid")).replaceAll("__VERSION__", version);

const files = {
  "cm-matrix.js": js,
  "cm-matrix.css": css,
  "compliance-matrix.webtemplate.liquid": template,
  "preview.html": preview()
};

if (check) {
  const stale = Object.entries(files).filter(([n, t]) => !existsSync(join(DIST, n)) || read(join(DIST, n)) !== t).map(([n]) => n);
  if (stale.length) {
    console.error("portal/dist is out of date: " + stale.join(", ") + "\nrun: (cd portal && npm run build)");
    process.exit(1);
  }
  console.log(`portal/dist is current (${Object.keys(files).length} files, version ${version})`);
} else {
  mkdirSync(DIST, { recursive: true });
  for (const [n, t] of Object.entries(files)) writeFileSync(join(DIST, n), t);
  const kb = s => (Buffer.byteLength(s) / 1024).toFixed(0) + " KB";
  console.log(`  cm-matrix.js   ${kb(js)}`);
  console.log(`  cm-matrix.css  ${kb(css)}  (design system ${Math.round(ddsBefore / 1024)} KB -> ${Math.round(ddsAfter / 1024)} KB after purge)`);
  console.log(`  compliance-matrix.webtemplate.liquid  version ${version}`);
  console.log(`  preview.html`);
}
