#!/usr/bin/env python3
"""
Build the Compliance Matrix home page from one design source and one metric
registry.

Inputs
    webpages/home/metrics.yaml          what each number on the page means
    webpages/home/src/home.source.html  the approved markup, with [[metric:k]]
    webpages/home/src/runtime.js        the client-side counter
    webpages/home/src/styles.css        optional supplemental CSS

Outputs (webpages/home/dist/, all generated - never edit them)
    home.webtemplate.html   Liquid web template. Counts run server-side through
                            fetchxml aggregates, so the page needs no JS and no
                            Web API configuration.
    home.pagecopy.html      Plain markup for the page-copy editor. Counts are
                            filled in by cm-metrics.js.
    cm-metrics.js           Generated query config + the runtime, one file to
                            paste into the page's JavaScript.
    cm-metrics.css          Copy of the supplemental CSS.
    preview.html            Standalone, opens in any browser, mock backend.
    SETUP-VALUES.md         The exact site settings and table permissions the
                            client-side path needs, derived from metrics.yaml.

Usage
    python3 tools/build_webpage.py            # write dist/
    python3 tools/build_webpage.py --check    # fail if dist/ is out of date
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
HOME = ROOT / "webpages" / "home"
SRC = HOME / "src"
DIST = HOME / "dist"

TOKEN = re.compile(r"\[\[metric:([a-z0-9_]+)\]\]")
UPDATED = re.compile(r"\[\[updated\]\]")

GENERATED = "GENERATED by tools/build_webpage.py - edit webpages/home/src/, not this file."

# Preview-only approximation of the portal theme. The real values come from the
# site's theme; these exist so the file opens in a browser and reads right.
PREVIEW_THEME = {
    "portalThemeColor1": ("#FFFFFF", "#212121"),
    "portalThemeColor2": ("#000E54", "#FFFFFF"),
    "portalThemeColor3": ("#F4F4F4", "#212121"),
    "portalThemeColor4": ("#EFEFEF", "#212121"),
    "portalThemeColor5": ("#F76900", "#FFFFFF"),
    "portalThemeColor6": ("#FFFFFF", "#212121"),
}

# A stand-in for /Geometric-*.png, which only exists on the portal.
PLACEHOLDER_SVG = (
    "data:image/svg+xml;utf8,"
    "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 600 340'%3E"
    "%3Crect width='600' height='340' fill='%23000E54'/%3E"
    "%3Cpath d='M0 340 L200 0 L400 340 Z' fill='%23F76900'/%3E"
    "%3Cpath d='M300 340 L500 60 L600 340 Z' fill='%23D74100'/%3E"
    "%3Ccircle cx='470' cy='80' r='54' fill='%23FFFFFF' opacity='0.14'/%3E"
    "%3C/svg%3E"
)


# ---------------------------------------------------------------------------
def load_metrics() -> dict:
    data = yaml.safe_load((HOME / "metrics.yaml").read_text(encoding="utf-8"))
    metrics = data.get("metrics") or {}
    if not metrics:
        raise SystemExit("metrics.yaml defines no metrics")
    for key, m in metrics.items():
        if "fallback" not in m:
            raise SystemExit(f"metric {key}: fallback is required")
        dv = m.get("dataverse")
        if not dv:
            raise SystemExit(f"metric {key}: a dataverse mapping is required")
        if dv.get("aggregate") not in ("count", "countdistinct"):
            raise SystemExit(f"metric {key}: aggregate must be count or countdistinct")
        if dv["aggregate"] == "countdistinct" and not dv.get("column"):
            raise SystemExit(f"metric {key}: countdistinct needs a column")
        sp = m.get("sharepoint")
        if sp and sp.get("aggregate") == "countdistinct" and not sp.get("field"):
            raise SystemExit(f"metric {key}: sharepoint countdistinct needs a field")
    return metrics


# ---------------------------------------------------------------------------
# Liquid web template
# ---------------------------------------------------------------------------
def fetchxml(key: str, m: dict) -> str:
    dv = m["dataverse"]
    distinct = dv["aggregate"] == "countdistinct"
    column = dv["column"] if distinct else dv["id"]
    agg = 'aggregate="countcolumn" distinct="true"' if distinct else 'aggregate="count"'

    conditions = []
    if dv.get("activeonly", True):
        conditions.append('<condition attribute="statecode" operator="eq" value="0" />')
    if dv.get("filter"):
        f = dv["filter"]
        conditions.append(
            f'<condition attribute="{f["column"]}" operator="eq" value="{f["value"]}" />'
        )

    lines = [
        '  <fetch aggregate="true">',
        f'    <entity name="{dv["entity"]}">',
        f'      <attribute name="{column}" alias="cm_value" {agg} />',
    ]
    if conditions:
        lines.append('      <filter type="and">')
        lines += [f"        {c}" for c in conditions]
        lines.append("      </filter>")
    lines += ["    </entity>", "  </fetch>"]
    return "\n".join(lines)


def build_webtemplate(source: str, metrics: dict) -> str:
    head = [
        "{% comment %}",
        f"  {GENERATED}",
        "",
        "  Compliance Matrix home page, server-rendered.",
        "",
        "  Each figure is a FetchXML aggregate run under the visitor's web role, so",
        "  the page needs no JavaScript and no Web API site settings. The tables",
        "  below need Read table permissions for whichever web role reaches this",
        "  page; without them the query returns nothing and the approved figure in",
        "  the markup is used instead, which is the intended degradation.",
        "",
        "  Tables read: " + ", ".join(sorted({m["dataverse"]["entity"] for m in metrics.values()})),
        "{% endcomment %}",
        "",
    ]

    for key, m in metrics.items():
        head += [
            f'{{% comment %}} {m.get("label", key)} {{% endcomment %}}',
            f"{{% fetchxml cm_{key}_q %}}",
            fetchxml(key, m),
            "{% endfetchxml %}",
            f"{{% assign cm_{key} = cm_{key}_q.results.entities[0].cm_value %}}",
            f"{{% if cm_{key} == blank %}}{{% assign cm_{key} = {m['fallback']} %}}{{% endif %}}",
            "",
        ]

    body = TOKEN.sub(lambda mo: "{{ cm_" + mo.group(1) + " }}", source)
    body = UPDATED.sub("Figures current as of {{ now | date: 'MMMM d, yyyy' }}", body)
    return "\n".join(head) + body


# ---------------------------------------------------------------------------
# Page copy + client-side script
# ---------------------------------------------------------------------------
def strip_source_comment(html: str) -> str:
    """Drop the authoring comment at the top of the source file."""
    return re.sub(r"\A<!--.*?-->\s*", "", html, flags=re.S)


def build_pagecopy(source: str, metrics: dict) -> str:
    def span(mo):
        key = mo.group(1)
        return (f'<span class="cm-metric" data-cm-metric="{key}">'
                f'{metrics[key]["fallback"]}</span>')

    body = TOKEN.sub(span, source)
    body = UPDATED.sub("&nbsp;", body)
    header = (
        "<!--\n"
        f"  {GENERATED}\n\n"
        "  Paste into the page's Copy field. Every figure carries the approved\n"
        "  number as its own text, so the page is correct before cm-metrics.js\n"
        "  runs and stays correct if the query is blocked.\n"
        "-->\n"
    )
    return header + body


def js_metric(key: str, m: dict) -> str:
    dv = m["dataverse"]
    distinct = dv["aggregate"] == "countdistinct"

    clauses = []
    if dv.get("activeonly", True):
        clauses.append("statecode eq 0")
    if dv.get("filter"):
        f = dv["filter"]
        clauses.append(f'{f["column"]} eq {f["value"]}')
    dv_filter = " and ".join(clauses)

    dv_js = (
        "{ set: %s, select: %s, distinct: %s, field: %s, filter: %s }"
        % (
            q(dv["set"]),
            q(dv["id"]),
            "true" if distinct else "false",
            q(dv.get("webapifield") or dv.get("column")) if distinct else "null",
            q(dv_filter) if dv_filter else "null",
        )
    )

    sp = m.get("sharepoint")
    if sp:
        sp_distinct = sp.get("aggregate") == "countdistinct"
        sp_filter = None
        if sp.get("filter"):
            f = sp["filter"]
            value = f["value"]
            value = value if isinstance(value, (int, float)) else "'%s'" % str(value).replace("'", "''")
            sp_filter = f'{f["field"]} eq {value}'
        sp_js = (
            "{ list: %s, distinct: %s, field: %s, filter: %s }"
            % (
                q(sp["list"]),
                "true" if sp_distinct else "false",
                q(sp.get("field")) if sp.get("field") else "null",
                q(sp_filter) if sp_filter else "null",
            )
        )
    else:
        sp_js = "null"

    return (
        f"  /* {m.get('label', key)} */\n"
        f"  {{\n"
        f"    key: {q(key)},\n"
        f"    fallback: {m['fallback']},\n"
        f"    dataverse: {dv_js},\n"
        f"    sharepoint: {sp_js}\n"
        f"  }}"
    )


def q(value) -> str:
    if value is None:
        return "null"
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_js(runtime: str, metrics: dict) -> str:
    head = [
        "/* " + GENERATED + " */",
        "/* ---------------------------------------------------------------------------",
        " * Compliance Matrix home page metrics",
        " * -------------------------------------------------------------------------",
        " * Paste this whole file into the page's JavaScript (Design Studio > the page",
        " * > ... > Edit code > JavaScript), or add it as a web file and reference it.",
        " *",
        " * Set backend below:",
        ' *   "dataverse"   Power Pages Web API. Needs the Webapi/* site settings and',
        " *                 Read table permissions - see dist/SETUP-VALUES.md.",
        ' *   "sharepoint"  SharePoint REST. Only works when this page is served from',
        " *                 the same SharePoint origin as the lists; a Power Pages site",
        " *                 is a different origin and the browser will block it.",
        ' *   "mock"        Renders the fallback figures. Used by preview.html.',
        " * ------------------------------------------------------------------------ */",
        "",
        "window.CM_CONFIG = {",
        '  backend: "dataverse",',
        "",
        "  // Only read when backend is \"sharepoint\". No trailing slash.",
        '  sharePointSite: "https://syr.sharepoint.com/sites/ComplianceMatrix",',
        "",
        "  // Counts are held in sessionStorage this long, so moving around the site",
        "  // does not re-run every query. 0 disables the cache.",
        "  cacheMinutes: 30,",
        "",
        "  // Page size when a count has to be taken by paging.",
        "  pageSize: 5000,",
        "",
        '  updatedPrefix: "Figures current as of ",',
        "",
        "  // true logs every request to the console.",
        "  debug: false",
        "};",
        "",
        "/* Query definitions, generated from webpages/home/metrics.yaml. */",
        "window.CM_METRICS = [",
        ",\n".join(js_metric(k, m) for k, m in metrics.items()),
        "];",
        "",
    ]
    return "\n".join(head) + "\n" + runtime


# ---------------------------------------------------------------------------
# Preview
# ---------------------------------------------------------------------------
PREVIEW_CSS = """
  :root { --su-orange: #F76900; --su-navy: #000E54; --su-link: #D74100; }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #212121;
    line-height: 1.55;
    background: #fff;
  }
  h1, h2, h3 { font-family: Georgia, "Times New Roman", serif; margin: 0 0 12px; line-height: 1.2; }
  h2 { font-size: 34px; }
  h3 { font-size: 20px; }
  p { margin: 0 0 16px; }
  a { color: var(--su-link); }
  .container { width: 100%; max-width: 1140px; margin: 0 auto; }
  .sectionBlockLayout { padding: 0 16px; }
  .sectionBlockLayout:not(:empty) { padding-top: 48px; padding-bottom: 48px; }
  .columnBlockLayout { padding: 0 15px; justify-content: center; }
  .col-lg-4 { flex-basis: 33.333%; }
  .col-lg-6 { flex-basis: 50%; }
  .col-lg-12 { flex-basis: 100%; }
  img { max-width: 100%; height: auto !important; object-fit: cover; }
  .button1 {
    align-self: flex-start;
    background: var(--su-orange);
    color: #fff;
    border: 0;
    padding: 13px 26px;
    font-size: 16px;
    font-weight: 600;
    cursor: pointer;
  }
  .button1:hover { background: var(--su-link); }
  .cm-preview-banner {
    background: var(--su-navy); color: #fff; font-size: 13px;
    padding: 10px 16px; text-align: center;
  }
  .cm-preview-banner code { color: #FFC07F; }
"""


def build_preview(pagecopy: str, metrics: dict) -> str:
    body = strip_source_comment(pagecopy)
    body = body.replace('src="/Geometric-4.png"', f'src="{PLACEHOLDER_SVG}"')
    body = body.replace('src="/Geometric-2.png"', f'src="{PLACEHOLDER_SVG}"')

    theme_css = "\n".join(
        f'  [data-component-theme="{name}"] {{ background: {bg}; color: {fg}; }}'
        for name, (bg, fg) in PREVIEW_THEME.items()
    )
    theme_css += (
        '\n  [data-component-theme="portalThemeColor2"] h1,'
        '\n  [data-component-theme="portalThemeColor2"] h2,'
        '\n  [data-component-theme="portalThemeColor2"] h3,'
        '\n  [data-component-theme="portalThemeColor5"] h1,'
        '\n  [data-component-theme="portalThemeColor5"] h2,'
        '\n  [data-component-theme="portalThemeColor5"] h3 { color: inherit; }'
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Compliance Matrix - home page preview</title>
<!-- {GENERATED} -->
<!--
  Local preview. Open it in a browser; it needs no server and no network.

  The figures come from the mock backend, which returns the fallbacks in
  metrics.yaml, so this shows the page exactly as a visitor sees it when the
  live query has not answered. Colours, spacing, and type here approximate the
  portal theme - the real site supplies its own.
-->
<link rel="stylesheet" href="cm-metrics.css">
<style>
{PREVIEW_CSS}
{theme_css}
</style>
</head>
<body>
<div class="cm-preview-banner">
  Local preview - figures served by the <code>mock</code> backend
  ({len(metrics)} metrics). Portal theme is approximated.
</div>
{body}
<script>window.CM_CONFIG_OVERRIDE = {{ backend: "mock", cacheMinutes: 0 }};</script>
<script src="cm-metrics.js"></script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Setup values
# ---------------------------------------------------------------------------
def build_setup(metrics: dict) -> str:
    tables: dict[str, set[str]] = {}
    for m in metrics.values():
        dv = m["dataverse"]
        fields = tables.setdefault(dv["entity"], set())
        fields.add(dv["id"])
        if dv["aggregate"] == "countdistinct":
            fields.add(dv["column"])
        if dv.get("activeonly", True):
            fields.add("statecode")
        if dv.get("filter"):
            fields.add(dv["filter"]["column"])

    lines = [
        f"<!-- {GENERATED} -->",
        "",
        "# Setup values",
        "",
        "Derived from `webpages/home/metrics.yaml`. Everything here is for the",
        "**client-side** path only (page copy + `cm-metrics.js` with the `dataverse`",
        "backend). The Liquid web template needs none of it - only the table",
        "permissions in the second section.",
        "",
        "## 1. Web API site settings",
        "",
        "Power Pages Design Studio, or the Portal Management app under **Site**",
        "**Settings**. Create these for the site that hosts the page.",
        "",
        "| Name | Value |",
        "|---|---|",
        "| `Webapi/error/innererror` | `true` (development only - remove before go-live) |",
    ]
    for table in sorted(tables):
        lines.append(f"| `Webapi/{table}/enable` | `true` |")
    for table, fields in sorted(tables.items()):
        lines.append(f"| `Webapi/{table}/fields` | `{','.join(sorted(fields))}` |")
    lines += [
        "",
        "`*` works in place of any field list and is easier to maintain, but it exposes",
        "every column on the table to the Web API for whoever holds the table",
        "permission. The lists above are the minimum these six figures need.",
        "",
        "A lookup is named by its logical name in the site setting and by",
        "`_<name>_value` in a `$select`; the generated script already uses the right",
        "form in each place.",
        "",
        "## 2. Table permissions",
        "",
        "One **Read** permission per table, **Global** scope, granted to the web role",
        "that reaches the page. Both paths need these - Liquid and the Web API are both",
        "filtered by them.",
        "",
        "| Table | Privilege | Scope |",
        "|---|---|---|",
    ]
    for table in sorted(tables):
        lines.append(f"| `{table}` | Read | Global |")
    lines += [
        "",
        "**Read this before granting the Anonymous Users role.** A Global Read",
        "permission is not scoped to counting - it lets that role read every row in",
        "the table through Liquid and, where the Web API is enabled, through",
        "`/_api/<table>`. Six aggregate figures on a public page are not worth",
        "publishing the obligation register to the internet. Either put the page",
        "behind authentication, or publish a snapshot instead (README, \"Public page",
        "without public data\").",
        "",
        f"Generated from {len(metrics)} metrics across {len(tables)} tables.",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
def build_all() -> dict[str, str]:
    metrics = load_metrics()
    source = strip_source_comment((SRC / "home.source.html").read_text(encoding="utf-8"))
    runtime = (SRC / "runtime.js").read_text(encoding="utf-8")
    styles = (SRC / "styles.css").read_text(encoding="utf-8")

    for key in TOKEN.findall(source):
        if key not in metrics:
            raise SystemExit(f"home.source.html uses [[metric:{key}]], "
                             f"which metrics.yaml does not define")
    used = set(TOKEN.findall(source))
    for key in metrics:
        if key not in used:
            raise SystemExit(f"metrics.yaml defines {key}, which the page never uses")

    pagecopy = build_pagecopy(source, metrics)
    return {
        "home.webtemplate.html": build_webtemplate(source, metrics),
        "home.pagecopy.html": pagecopy,
        "cm-metrics.js": build_js(runtime, metrics),
        "cm-metrics.css": f"/* {GENERATED} */\n" + styles,
        "preview.html": build_preview(pagecopy, metrics),
        "SETUP-VALUES.md": build_setup(metrics),
    }


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if dist/ differs from a fresh build")
    args = ap.parse_args(argv)

    files = build_all()

    if args.check:
        stale = []
        for name, text in files.items():
            path = DIST / name
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        if stale:
            print("dist/ is out of date: " + ", ".join(sorted(stale)))
            print("run: python3 tools/build_webpage.py")
            return 1
        print(f"dist/ is current ({len(files)} files)")
        return 0

    DIST.mkdir(parents=True, exist_ok=True)
    for name, text in files.items():
        (DIST / name).write_text(text, encoding="utf-8")
        print(f"  wrote webpages/home/dist/{name}")
    print(f"{len(files)} files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
